#!/usr/bin/ansible-playbook
---
- name: Install Kubernetes repo
  hosts: k8s_cluster
  roles:
    - k8s/repo

- name: Install Kubernetes control machine
  hosts: admin
  roles:
    - k8s/admin
    - k8s/node

- name: Install Kubernetes worker node
  hosts: node
  roles:
    - k8s/node
