#!/usr/bin/ansible-playbook
---
- name: Install Kubernetes
  hosts: k8s_cluster
  roles:
    - k8s/repo
    - k8s/node

- name: Install Kubernetes control machine
  hosts: admin
  roles:
    - k8s/admin
