---
- name: Run node system prep tasks
  import_tasks: ./sysprep.yml

- name: Run packages tasks
  import_tasks: ./packages.yml

- name: Install kubeadm and kubelet
  apt:
    name: '{{ item }}={{ k8s_version }}'
  loop:
    - kubeadm
    - kubelet

- name: Hold the kubeadm and kubelet package, prevent upgrades
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubeadm
    - kubelet

- name: Pull the kubeadm images
  command: kubeadm config images pull
