---
- name: Turn off swap
  command: swapoff -a
  
- name: Disable swap in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '.*\sswap\s+sw\s+.*'
    state: absent
  notify: systemctl daemon-reload

- name: Enable kernel modules for Kubernetes at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |-
      overlay
      br_netfilter

- name: Load kernel modules for Kubernetes
  command: 'modprobe {{ item }}'
  loop:
    - overlay
    - br_netfilter

- name: Add sysctl parameters for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |-
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Update sysctl runtime for Kubernetes
  command: sysctl -p /etc/sysctl.d/k8s.conf
